### ISSUE TITLE
Need feedback :)

### ISSUE THREAD

**Issue by moul** [multiarch/dockerfile#2]

**Comment by moul** [comment]
My favorite ones:
1. **method H**: may works without any bash/makefile, but it needs to patch Docker to support `FROM ${ARG}`
2. **method G**: works out of the box, get multiarch support thanks to bash/makefile, does not require to patch Docker

Both of them are using a unique Dockerfile :heart:

**Comment by QuentinPerez** [comment]
If we can patch docker the **method H** else the **method G or E**

**Comment by aimxhaisse** [comment]
I'd advocate for G and H too.

I prefer by far the H method but I guess it's quite a big upstream change.

G looks like the best compromise if H is not possible ; I don't like the fact that there are 'two' ways used to express the differences between arch, but I don't see how we could have only one here with multi-line support, without modifying the Dockerfile DSL.
